version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smartsync
    ports:
      - "5433:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  nats:
    image: nats:latest
    ports:
      - "4222:4222"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # НОВОЕ: База данных для микросервиса аудита
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: