version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smartsync
    ports:
      - "5433:5432"

  nats:
    image: nats:latest
    ports:
      - "4222:4222"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"